baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
theme: 
  - "PaperMod"
params:
  defaultTheme: auto

  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  # socialIcons: # optional
  #   - name: "<platform>"
  #     url: "<link>"
  #   - name: "<platform 2>"
  #     url: "<link2>"
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
