baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
theme: 
  - "PaperMod"
params:
  defaultTheme: auto

  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
